language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install pip --upgrade
    - pip install pytest --upgrade
    # - pip install pylint --upgrade

# command to run tests, e.g. python setup.py test
script:
    - python setup.py sdist --format=zip
    - pip install dist/pynmea2*.zip
    - py.test
    # - pylint -E pynmea2 ## pylint is not backwards compatible with itself

after_success:
    - pip install coveralls coverage
    - PYTHONPATH=. coverage run --source=pynmea2 -m pytest
    - coverage report
    - coveralls
